# Generated by Django 4.1.6 on 2023-02-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImdbTop250Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.IntegerField(blank=True, null=True)),
                ("movie_title", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("star_cast", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "imdb_top_250_movies", "managed": False,},
        ),
    ]
