# Generated by Django 4.1.6 on 2023-02-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="imdbtop250movies", options={},),
    ]
